logging.level:
  root: info

spring:

  application.name: feed

  cloud:
    function:
      definition: supplier|publisher

management:
  # server.port: 9090
  endpoints.web.exposure.include: '*' 
  endpoint.health.show-details: always 

springdoc:
  # use-management-port: true
  swagger-ui.use-root-path: false
